theme: jekyll-theme-cayman
title: Language2Pose
description: 'Natural Language Grounded Pose Forecasting'
authors: Chaitanya Ahuja, Louis-Philippe Morency
affiliations: Carnegie Mellon University
google_analytics: UA-59835835-3
